- hosts: all
  become: yes
  remote_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  pre_tasks:
    - name: "Install python3-apt"
      raw: |
        sudo apt-get update -qq
        sudo apt-get install -y python3-apt

    - name: "Install Essential Python Dependencies"
      raw: |
        sudo apt-get update -qq
        sudo apt-get install -y python3-distutils python3-apt python3-dev

    - name: "Verify Python SSL Module"
      raw: |
        python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
      register: ssl_check
      failed_when: "ssl_check.rc != 0"

  tasks:
    - name: Install Ansible
      raw: |
        sudo apt-get update -qq
        sudo apt-get install -y ansible

    - name: Reinstall python3-apt
      raw: |
        sudo apt-get install --reinstall -y python3-apt

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Debug Docker version
      debug:
        var: docker_version.stdout

    - name: Add user to Docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Copy hello-world-app directory
      copy:
        src: ./hello-world-app/
        dest: /home/azureuser/hello-world-app/

    - name: Build Docker image
      docker_image:
        name: hello-world-app
        build:
          path: /home/azureuser/hello-world-app/
        source: build
      ignore_errors: no

    - name: Run Docker container
      docker_container:
        name: hello-world-app
        image: hello-world-app
        state: started
        ports:
          - "80:80"
      ignore_errors: no
