- hosts: all
  become: yes
  # Pre-tasks to handle Python 3 installation
  pre_tasks:
    - name: Install Python 3 if not present
      raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      changed_when: false

    - name: Set Ansible Python Interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
  tasks:
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Start and enable Docker service
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Add user to Docker group
    - name: Add user to Docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    # Copy the hello-world-app directory to the target machine
    - name: Copy hello-world-app directory
      copy:
        src: ./hello-world-app/  # Source directory (checked out by GitHub Actions)
        dest: /home/azureuser/hello-world-app/

    # Build the Docker image
    - name: Build Docker image
      docker_image:
        name: hello-world-app
        build:
          path: /home/azureuser/hello-world-app/  # Path to the copied directory
        source: build

    # Run the Docker container
    - name: Run Docker container
      docker_container:
        name: hello-world-app
        image: hello-world-app
        state: started
        ports:
          - "80:80"  # Expose port 80 on the VM
