name: Deploy Application
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH access
      - name: Set up SSH access
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Add target server to known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan 40.88.13.22 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Step 4: Verify Docker installation
      - name: Verify Docker installation
        run: |
          docker --version

      # Step 5: Build and run the Docker container
      - name: Build and run Docker container
        run: |
          echo "🚀 Starting deployment to production..."
          docker build --build-arg SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" -t ansible-python3.8 .
          docker run ansible-python3.8
          echo "✅ Successfully deployed application!"

      # Step 6: Print Docker logs if the container fails
      - name: Print Docker logs if the container fails
        if: ${{ failure() }}
        run: |
          docker logs $(docker ps -aqf "ancestor=ansible-python3.8")

      # Step 7: Clean up Docker resources
      - name: Clean up Docker resources
        if: ${{ always() }}
        run: |
          docker system prune -f
